import { defineConfig } from "tinacms";

export default defineConfig({
  branch:
    process.env.GITHUB_BRANCH ||
    process.env.VERCEL_GIT_COMMIT_REF ||
    process.env.HEAD ||
    "master",
  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID || "",
  token: process.env.TINA_TOKEN || "",

  build: {
    outputFolder: "admin",
    publicFolder: "public",
  },
  media: {
    tina: {
      mediaRoot: "",
      publicFolder: "public",
    },
  },
  schema: {
    collections: [
      {
        name: "siteSettings",
        label: "Site Settings",
        path: "content",
        match: { include: "siteSettings" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "title", label: "Site Title", required: true },
          { type: "string", name: "description", label: "Meta Description", required: true },
        ],
      },
      {
        name: "hero",
        label: "Hero Section",
        path: "content",
        match: { include: "hero" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "badge", label: "Badge Text" },
          { type: "string", name: "title", label: "Title" },
          { type: "string", name: "titleEmphasis", label: "Title Emphasis (italic)" },
          { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
          { type: "string", name: "ctaPrimary", label: "Primary CTA Text" },
          { type: "string", name: "ctaSecondary", label: "Secondary CTA Text" },
          {
            type: "object",
            name: "languages",
            label: "Languages",
            list: true,
            fields: [
              { type: "string", name: "flag", label: "Flag Code (2-letter)" },
              { type: "string", name: "alt", label: "Alt Text" },
              { type: "string", name: "name", label: "Language Name" },
            ],
          },
          {
            type: "object",
            name: "stats",
            label: "Statistics",
            list: true,
            fields: [
              { type: "string", name: "value", label: "Value" },
              { type: "string", name: "label", label: "Label" },
            ],
          },
        ],
      },
      {
        name: "about",
        label: "About Section",
        path: "content",
        match: { include: "about" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "sectionTag", label: "Section Tag" },
          { type: "string", name: "sectionTitle", label: "Section Title" },
          { type: "string", name: "lead", label: "Lead Text", ui: { component: "textarea" } },
          { type: "string", name: "paragraphs", label: "Paragraphs", list: true },
          {
            type: "object",
            name: "cards",
            label: "Cards",
            list: true,
            fields: [
              { type: "string", name: "icon", label: "Icon (FontAwesome class)" },
              { type: "string", name: "title", label: "Title" },
              { type: "string", name: "desc", label: "Description" },
            ],
          },
          { type: "string", name: "guaranteesTitle", label: "Guarantees Title" },
          { type: "string", name: "guarantees", label: "Guarantees", list: true },
        ],
      },
      {
        name: "services",
        label: "Services Section",
        path: "content",
        match: { include: "services" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "sectionTag", label: "Section Tag" },
          { type: "string", name: "sectionTitle", label: "Section Title" },
          { type: "string", name: "sectionDesc", label: "Section Description", ui: { component: "textarea" } },
          {
            type: "object",
            name: "services",
            label: "Services",
            list: true,
            fields: [
              { type: "string", name: "icon", label: "Icon (FontAwesome class)" },
              { type: "string", name: "title", label: "Title" },
              { type: "string", name: "desc", label: "Description" },
            ],
          },
          { type: "string", name: "ctaIcon", label: "CTA Icon" },
          { type: "string", name: "ctaTitle", label: "CTA Title" },
          { type: "string", name: "ctaDesc", label: "CTA Description" },
          { type: "string", name: "ctaButton", label: "CTA Button Text" },
        ],
      },
      {
        name: "citizenship",
        label: "Citizenship Section",
        path: "content",
        match: { include: "citizenship" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "sectionTag", label: "Section Tag" },
          { type: "string", name: "sectionTitle", label: "Section Title" },
          { type: "string", name: "sectionDesc", label: "Section Description", ui: { component: "textarea" } },
          {
            type: "object",
            name: "ways",
            label: "Ways to Get Citizenship",
            list: true,
            fields: [
              { type: "string", name: "icon", label: "Icon" },
              { type: "string", name: "title", label: "Title" },
              { type: "string", name: "desc", label: "Description" },
            ],
          },
          { type: "string", name: "stepsTitle", label: "Steps Title" },
          {
            type: "object",
            name: "steps",
            label: "Steps",
            list: true,
            fields: [
              { type: "number", name: "num", label: "Step Number" },
              { type: "string", name: "title", label: "Title" },
              { type: "string", name: "time", label: "Time/Duration" },
            ],
          },
          { type: "string", name: "faqTitle", label: "FAQ Title" },
          {
            type: "object",
            name: "faqs",
            label: "FAQs",
            list: true,
            fields: [
              { type: "string", name: "q", label: "Question" },
              { type: "string", name: "a", label: "Answer", ui: { component: "textarea" } },
            ],
          },
        ],
      },
      {
        name: "process",
        label: "Process Section",
        path: "content",
        match: { include: "process" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "sectionTag", label: "Section Tag" },
          { type: "string", name: "sectionTitle", label: "Section Title" },
          {
            type: "object",
            name: "steps",
            label: "Steps",
            list: true,
            fields: [
              { type: "string", name: "num", label: "Step Number" },
              { type: "string", name: "title", label: "Title" },
              { type: "string", name: "desc", label: "Description" },
            ],
          },
        ],
      },
      {
        name: "testimonials",
        label: "Testimonials Section",
        path: "content",
        match: { include: "testimonials" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "sectionTag", label: "Section Tag" },
          { type: "string", name: "sectionTitle", label: "Section Title" },
          {
            type: "object",
            name: "reviews",
            label: "Reviews",
            list: true,
            fields: [
              { type: "string", name: "text", label: "Review Text", ui: { component: "textarea" } },
              { type: "string", name: "author", label: "Author/Category" },
            ],
          },
        ],
      },
      {
        name: "contact",
        label: "Contact Section",
        path: "content",
        match: { include: "contact" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "sectionTag", label: "Section Tag" },
          { type: "string", name: "sectionTitle", label: "Section Title" },
          {
            type: "object",
            name: "subjects",
            label: "Form Subjects",
            list: true,
            fields: [
              { type: "string", name: "value", label: "Value" },
              { type: "string", name: "label", label: "Label" },
            ],
          },
          {
            type: "object",
            name: "formLabels",
            label: "Form Labels",
            fields: [
              { type: "string", name: "name", label: "Name Label" },
              { type: "string", name: "namePlaceholder", label: "Name Placeholder" },
              { type: "string", name: "email", label: "Email Label" },
              { type: "string", name: "emailPlaceholder", label: "Email Placeholder" },
              { type: "string", name: "subject", label: "Subject Label" },
              { type: "string", name: "subjectPlaceholder", label: "Subject Placeholder" },
              { type: "string", name: "message", label: "Message Label" },
              { type: "string", name: "messagePlaceholder", label: "Message Placeholder" },
              { type: "string", name: "submit", label: "Submit Button Text" },
            ],
          },
          {
            type: "object",
            name: "contactInfo",
            label: "Contact Info",
            list: true,
            fields: [
              { type: "string", name: "icon", label: "Icon" },
              { type: "string", name: "label", label: "Label" },
              { type: "string", name: "value", label: "Display Value" },
              { type: "string", name: "href", label: "Link URL" },
              { type: "boolean", name: "isLink", label: "Is Clickable Link" },
              { type: "boolean", name: "external", label: "Open in New Tab" },
            ],
          },
        ],
      },
      {
        name: "header",
        label: "Header / Navigation",
        path: "content",
        match: { include: "header" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "logoText", label: "Logo Text" },
          { type: "string", name: "logoAccent", label: "Logo Accent" },
          {
            type: "object",
            name: "navLinks",
            label: "Nav Links",
            list: true,
            fields: [
              { type: "string", name: "href", label: "Link URL" },
              { type: "string", name: "label", label: "Link Label" },
            ],
          },
          { type: "string", name: "ctaLabel", label: "CTA Button Label" },
        ],
      },
      {
        name: "footer",
        label: "Footer",
        path: "content",
        match: { include: "footer" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "logoText", label: "Logo Text" },
          { type: "string", name: "logoAccent", label: "Logo Accent" },
          { type: "string", name: "description", label: "Description" },
          { type: "string", name: "phone", label: "Phone Number" },
          { type: "string", name: "phoneHref", label: "Phone Link" },
          { type: "string", name: "email", label: "Email" },
          { type: "string", name: "emailHref", label: "Email Link" },
          { type: "string", name: "copyright", label: "Copyright Text" },
          { type: "string", name: "legal", label: "Legal Text" },
        ],
      },
      {
        name: "mascot",
        label: "Mascot",
        path: "content",
        match: { include: "mascot" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "tooltip", label: "Tooltip Text", ui: { component: "textarea" } },
          { type: "string", name: "altText", label: "Image Alt Text" },
          { type: "string", name: "image", label: "Image Path" },
        ],
      },
      {
        name: "mobileBanner",
        label: "Mobile Banner",
        path: "content",
        match: { include: "mobileBanner" },
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "title", label: "Title" },
          { type: "string", name: "description", label: "Description" },
        ],
      },
    ],
  },
});
